mod conditions;
mod config_cmds;
mod data;
mod db_viewer;
mod folders;
mod rules;
mod watcher_cmds;

use std::sync::{Arc, Mutex};

use crate::config::AppConfig;
use crate::db::Database;
use crate::watcher::FileWatcher;

pub struct AppState {
    pub config: Arc<Mutex<AppConfig>>,
    pub db: Arc<Database>,
    pub watcher: Arc<Mutex<FileWatcher>>,
}

// ── Re-exports ──────────────────────────────────────────────
// Wildcard re-exports are needed so tauri::generate_handler! can find
// the hidden __cmd__ items generated by #[tauri::command].

pub use conditions::*;
pub use config_cmds::*;
pub use data::*;
pub use db_viewer::*;
pub use folders::*;
pub use rules::*;
pub use watcher_cmds::*;
